src/Entity/News.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
#[ApiResource]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $created_at;

    #[ORM\OneToMany(mappedBy: 'news', targetEntity: Files::class, cascade: ['all'])]
    private $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Files>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(Files $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setNews($this);
        }

        return $this;
    }

    public function removeFile(Files $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getNews() === $this) {
                $file->setNews(null);
            }
        }

        return $this;
    }
}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use PhpParser\Node\Stmt\Label;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description',CkEditorType::class, [

                'label' => false,
                ])
                ->add('files',FileType::class,[
                    'label' => false,
                    'multiple' => true,
                    'mapped'=> false,
                    'required'=> false,
                    
            
                
                ])
            ->add('created_at',DateTimeType::class,[
                'widget' => "single_text",
                
                'data' => new \DateTime("now")
            ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Entity\Files;
use App\Form\NewsType;
use App\Repository\NewsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/news')]
class NewsController extends AbstractController
{
    #[Route('/', name: 'app_news_index', methods: ['GET'])]
    public function index(NewsRepository $newsRepository): Response
    {
        return $this->render('news/index.html.twig', [
            'news' => $newsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_news_new', methods: ['GET', 'POST'])]
    public function new(Request $request, NewsRepository $newsRepository): Response
    {
        $news = new News();
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $date = new \DateTimeImmutable('now');
            $news->setCreatedAt($date);

            $files = $form->get('files')->getData();
            foreach($files as $file){
                // Je génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $file->guessExtension();

                // Je copie le fichier dans le dossier uploads
                $file->move(
                    $this->getParameter('videos_directory'),
                    $fichier
                );

                // Je stocke le document dans la BDD (nom du fichier)
                $file= new Files();
                $file->setPath($fichier);
            
                $news->addFile($file);
            }

            $newsRepository->add($news, true);

            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('news/new.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_show', methods: ['GET'])]
    public function show(News $news): Response
    {
        return $this->render('news/show.html.twig', [
            'news' => $news,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_news_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, News $news, NewsRepository $newsRepository): Response
    {
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newsRepository->add($news, true);

            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('news/edit.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_delete', methods: ['POST'])]
    public function delete(Request $request, News $news, NewsRepository $newsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$news->getId(), $request->request->get('_token'))) {
            $newsRepository->remove($news, true);
        }

        return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/news/_delete_form.html.twig
<form method="post" action="{{ path('app_news_delete', {'id': news.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
    <button class="btn">Delete</button>
</form>

templates/news/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block body %}
    <h1>Edit News</h1>

    {{ include('news/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_news_index') }}">back to list</a>

    {{ include('news/_delete_form.html.twig') }}
{% endblock %}

templates/news/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}News index{% endblock %}

{% block body %}
    <h1>News index</h1>



	{{ block("MenuTop", "Menus/MenuTop.html.twig") }}
	<div class="app-main">
		{{ block("MenuLeft", "Menus/MenuLeft.html.twig") }}

		<style>
			form {
				display: contents;
			}
			.select2 {
				width: 100% !important;


				font-size: 1rem;
				font-weight: 400;
				line-height: 1.5;
				color: #495057;
				background-color: #fff;
				background-clip: padding-box;

				border-radius: 0.25rem;
			}
			.page,
			.current,
			.previous,
			.first,
			.next,
			.last {
				border: solid 1px;
				padding: 5px;
				margin: 2px;
			}
		</style>
		<div class="app-main__outer">
			<div class="app-main__inner">
				<div class="app-page-title">
					<div class="page-title-wrapper">
						<div class="page-title-heading">
							<div class="page-title-icon">
								<i class="pe-7s-notebook icon-gradient bg-strong-bliss"></i>
							</div>
							<div>News
								<div class="page-title-subheading">Liste des news</div>
							</div>
						</div>
						<div class="page-title-actions">

							<div class="d-inline-block dropdown">
								<a href="{{ path('app_news_new') }}">
									<button class="btn-shadow btn btn-primary">
										<span class="btn-icon-wrapper pr-2 opacity-7">
											<i class="fa fa-plus fa-w-20"></i>
										</span>
										Ajouter
									</button>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="tabs-animation">
					<div class="main-card mb-3 card">
						<div class="card-body">
						

							<div id="example_wrapper" class="dataTables_wrapper dt-bootstrap4">

								<div class="row">
									<div class="col-sm-12">
										<table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for news in news %}
            <tr>
                <td>{{ news.id }}</td>
                <td>{{ news.titre }}</td>
              
                <td>{{ news.createdAt ? news.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_news_show', {'id': news.id}) }}">show</a>
                    <a href="{{ path('app_news_edit', {'id': news.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
									

									</div>
								</div>


							</div>
						</div>
					</div>


				</div>
			</div>

		</div>
	</div>


	<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

{% endblock %}

templates/news/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %} Nouvelle article{% endblock %}

{% block body %}
   {{ block("MenuTop", "Menus/MenuTop.html.twig") }}
   <div class="app-main">
    {{ block("MenuLeft", "Menus/MenuLeft.html.twig") }}


 <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="app-page-title">
                        <div class="page-title-wrapper">
                            <div class="page-title-heading">
                                <div class="page-title-icon">
                                    <i class="lnr-users icon-gradient bg-strong-bliss"></i>
                                </div>
                              <div>Ajouter un article
                                    <div class="page-title-subheading"> Créez votre article</div>
                                </div>
                            </div>
                           <div class="page-title-actions">
                        
                            <div class="d-inline-block dropdown">
                            <a href="{{path('app_news_index')}}">
                                <button  class="mb-2 mr-2 btn btn-shadow btn-outline-2x btn-outline-secondary">
                                    <span class="btn-icon-wrapper pr-2 opacity-7">
                                        <i class="fa fa-arrow-circle-left fa-w-20"></i>
                                    </span>
                                    Retour à la liste
                                </button>
                               </a>
                            </div>
                        </div>
                        </div>
                    </div>
               
                    <div class="tabs-animation"> 
                     <div class="main-card mb-3 card">
                        <div class="card-body">
                            
                                <div class="row">
                                    <div class="col-sm-12">
                                    {{ include('news/_form.html.twig') }}
						
                                    
                                    </div>
                                </div>
                        
                        
                        </div>
                    </div>
                    
         
                     
                    </div>
                </div>
   
    </div> 


    </div>

{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block body %}
    <h1>News</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ news.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ news.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ news.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ news.createdAt ? news.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_news_index') }}">back to list</a>

    <a href="{{ path('app_news_edit', {'id': news.id}) }}">edit</a>

    {{ include('news/_delete_form.html.twig') }}
{% endblock %}